config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  #post '/questions', to: 'questions#create'
  #patch '/questions/:id', to: 'questions#update'
  #delete '/questions/:id', to: 'questions#destroy'
  resources :questions
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[update show destroy edit]
  def create
    question = Question.create(question_params)
    ## question_params = params.require(:question).permit(:body, :user_id)
    ## question = Question.create(question_params)
    #question = Question.create(
    #  body: params[:question][:body],
    #  user_id: params[:question][:user_id]
    #)
    #flash[:notice] = "Ваш новый вопрос создан!"
    redirect_to question_path(question), notice: "Новый вопрос создан!"
  end

  def update
    #@question = Question.find(params[:id]) - убрали из-за before_action
    @question.update(question_params)
    #@question.update( 
    #  body: params[:question][:body],
    #  user_id: params[:question][:user_id] 
    #) - убрали из-за question_params

    redirect_to question_path(@question), notice: "Сохранили вопрос!"
  end

  def destroy
    #@question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path, notice: "Удалили вопрос!"
  end

  def show
    #@question = Question.find(params[:id])
  end

  def index
    @question = Question.new
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def edit
    #@question = Question.find(params[:id])
  end

  private

  def question_params
    params.require(:question).permit(:body, :user_id)
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])
    user&.authenticate(user_params[:password]) #из-за & метод не выдаст ошибку, если юзер не найдётся

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: "Вы вошли на сайт"
    else
      flash.now[:alert] = "Неправильный email или пароль"

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: "Вы вышли из аккаунта"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    session[:current_time] = Time.now
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:name,
      :nickname, :email, :password)
    
    User.create(user_params)
    
    redirect_to root_path, notice: "Вы успешно зарегались!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclinator(count, one, few, many)
    return many if (count%100).between?(11, 14)

    case count % 10
      when 1 then one
      when 2..4 then few
      else 
        many
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <div class="navbar">
        <p class="title-sm text-bold"><%= link_to "Ask me!", root_path %></p>
        <div>
          <% if current_user.present? %>
           <%= content_tag 'span', "@#{current_user.nickname}", class: "mr-sm" %>
           <%= button_to "Выйти", session_path, method: :delete %>
          <% else %>
            <%= link_to "Регистрация", new_user_path, class: "button button-yellow mr-sm" %>
            <%= link_to "Вход", new_session_path, class: "button button-yellow" %>
          <% end %>
        </div>
      </div>
      
      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice]%></p>
      <% elsif flash[:alert].present? %>
        <p class="mb mt message message-alert"><%= flash[:alert]%></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question do |form| %>
  <p><%= form.label :body, "Текст вопроса" %></p>
  <p><%= form.text_area :body, rows: 5, class: "form-text-area" %></p>
  <p class="mt"><%= form.label :user_id %></p>
  <p><%= form.text_field :user_id, class: "form-text-field"%></p>
  <p class="mt"><%= form.submit "Сохранить", class: "button button-main"%></p>
<% end %>

app/views/questions/_question.html.erb
<div class="mb-sm">
  <%= question.body %>
</div>

<div class="text-sm question-footer">
  <div class="textgrey">
    <%= l(question.created_at, format: :short) %>
  </div>

  <div>
    <%= link_to fa_icon('pencil'), edit_question_path(question),
      title: "Изменить вопрос" %>
    <%= button_to fa_icon('trash-o'), question_path(question),
      method: :delete, title: "Удалить вопрос" %>
  </div>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Редактирование вопроса <%= @question.id %></h2>
  
<!-- когда отправляем в form_with уже существующий вопрос, 
он понимает, что нужно слать запрос PATCH вместо POST и путь должен
быть не /questions, а /questions/id -->

  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container">
  <p class="mt">
    <%= link_to "Создать новый вопрос", new_question_path, class: "button button-main" %>
  </p>
  <p class ="mt">
    <%= render "form", question: @question %>
  </p>
</div>

<div class="container mt-sm">
  <h2 class="title-lg">
    <%= @questions.count %>
    <%= inclinator(@questions.count, "вопрос", "вопроса", "вопросов") %>
  </h2>
</div>

<% @questions.each do |question| %>
  <!-- <p><%= link_to "Вопрос #{question.id}", "/questions/#{question.id}" %>  -->
  <!-- <p class="mb-sm"><%= link_to "Вопрос #{question.id}", question_path(id: question.id) %> -->
  <div class="mt-sm container">  
    <%= render question %>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg">Новый вопрос</h2>
  <!--
  <form action="/questions" method="POST">
    <p><label for="question[body]">Текст вопроса</label></p>
    <p><textarea name="question[body]" rows=5></textarea></p>
    <p><label for="question[user_id]">User id</label></p>
    <p><input type="number" name="question[user_id]"></p>
    <input type="submit" value="Создать"></p>
  </form>
  -->
  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Вопрос <%= @question.id %></h2>
  
  <!-- <%= render "question", question: @question %> -->
  <%= render @question %>

  <p class="mt"><%= link_to "Все вопросы", questions_path %></p>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title">Присоединяйся и спрашивай!</h2>

  <div class="mt">
    <%= form_with model: @user do |form| %>
      <p><%= form.label :name, "Ваше имя" %></p>
      <p><%= form.text_field :name, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :nickname, "Ник на сайте" %></p>
      <p><%= form.text_field :nickname, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :email %></p>
      <p><%= form.text_field :email, class: "form-text-field" %></p>

      <p class="mt"><%= form.label :password, "Пароль" %></p>
      <p><%= form.password_field :password, class: "form-text-field" %></p>

      <p class="mt-lg"><%= form.submit "Зарегистрироваться",
        class: "button button-main" %></p>
    <% end %>
  </div>
</div>